service: default

runtime: nodejs20

instance_class: B1
basic_scaling:
  max_instances: 1

handlers:
# Serve all static files with url ending with a file extension
- url: /assets
  secure: always
  static_dir: dist/assets
- url: /fonts
  secure: always
  static_dir: dist/fonts
- url: /icons
  secure: always
  static_dir: dist/icons
- url: /images
  secure: always
  static_dir: dist/images
- url: /lotties
  secure: always
  static_dir: dist/lotties
- url: /sounds
  secure: always
  static_dir: dist/sounds
- url: /favicon.png
  secure: always
  static_files: dist/favicon.png
  upload: dist/favicon.png

# Catch all handler to index.html
- url: /.*
  secure: always
  static_files: dist/index.html
  upload: dist/index.html
